define(function(require){
	require('underscore');
	require('bootstrap');
	require('backbone');
	require('select2');
	require('app/base/app');
	require('app/base/nav');
	require('app/view/view');
	require('app/boot');
});